apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-gitops
